### ISSUE TITLE
184198

### ISSUE THREAD

**Issue by PlumbDawg** [dduzgun-security/github-self-hosted-runners#3]

**Comment by dduzgun-security** [comment]
Any description @PlumbDawg ?

**Comment by PlumbDawg** [comment]
> Any description @PlumbDawg ?

I am trying to learn all this Bro and I am freaking lost! What do I do? Who can tutor me thru this chaos Bro?

**Comment by dduzgun-security** [comment]
Sorry about the delay @PlumbDawg I think this can help you: https://skills.github.com/
